# Generated by Django 5.1 on 2024-09-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='cidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='curso',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
